# Generated by Django 3.2.4 on 2021-06-11 04:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('animalia_code', models.CharField(max_length=20, unique=True)),
                ('primitiva_name', models.CharField(max_length=150)),
                ('procedence', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'M - Male subject'), (2, 'F - Female subject')])),
                ('status', models.IntegerField(choices=[(1, 'Deceased - Subject died for natural causes'), (2, 'Deceased by human - Subject died due to human sources'), (3, 'Sick - Subject is sick and observated by caretakers'), (4, "Crippled - Subject is healthy but have certain conditions that doesn't allow it to live normally"), (5, 'Healthy - Subject is healthy and good conditions'), (6, 'In heat - Subject is in heat trying to copulate'), (7, 'Pregnant - Female subject in pregnancy')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('variations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('cientific_name', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(0, 'LC - Preocupación menor'), (1, 'NT - Casi amenazada'), (2, 'VU - Vulnerable'), (3, 'EN - En peligro'), (4, 'CR - En peligro crítico'), (5, 'EW - Extinta en estado silvestre'), (6, 'EX - Extinta')])),
            ],
        ),
        migrations.CreateModel(
            name='Plantae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('plantae_code', models.CharField(max_length=20, unique=True)),
                ('primitiva_name', models.CharField(max_length=150)),
                ('procedence', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'M - Male subject'), (2, 'F - Female subject')])),
                ('size', models.FloatField()),
                ('weight', models.FloatField()),
                ('taxonomic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specie', to='primitiva_ecosystem.taxonomicgroup', verbose_name='Taxonomic Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EcosystemVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('main_ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='primitiva_ecosystem.ecosystem', verbose_name='Main ecosystem')),
                ('sub_ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='primitiva_ecosystem.ecosystem', verbose_name='Sub ecosystem')),
            ],
        ),
        migrations.CreateModel(
            name='AnimaliaObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', models.TextField()),
                ('natural_performance', models.TextField()),
                ('overall_size', models.FloatField()),
                ('head_size', models.FloatField()),
                ('body_size', models.FloatField()),
                ('extremities_size', models.FloatField()),
                ('overall_weight', models.FloatField()),
                ('head_weight', models.FloatField()),
                ('body_weight', models.FloatField()),
                ('extremities_weight', models.FloatField()),
                ('subject_evolution', models.TextField()),
                ('current_status', models.IntegerField(choices=[(1, 'Deceased - Subject died for natural causes'), (2, 'Deceased by human - Subject died due to human sources'), (3, 'Sick - Subject is sick and observated by caretakers'), (4, "Crippled - Subject is healthy but have certain conditions that doesn't allow it to live normally"), (5, 'Healthy - Subject is healthy and good conditions'), (6, 'In heat - Subject is in heat trying to copulate'), (7, 'Pregnant - Female subject in pregnancy')])),
                ('symptoms', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_subject', to='primitiva_ecosystem.animalia', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='AnimaliaLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_location', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_witnessed', models.DateTimeField()),
                ('animalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='primitiva_ecosystem.animalia', verbose_name='Subject')),
            ],
        ),
        migrations.AddField(
            model_name='animalia',
            name='taxonomic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='primitiva_ecosystem.taxonomicgroup', verbose_name='Taxonomic Group'),
        ),
    ]
