# Generated by Django 3.2.4 on 2021-06-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primitiva_ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalia',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='animalialocations',
            options={'verbose_name': 'Animal Location', 'verbose_name_plural': 'Animal Locations'},
        ),
        migrations.AlterModelOptions(
            name='animaliaobservation',
            options={'verbose_name': 'Animal Observation', 'verbose_name_plural': 'Animal Observations'},
        ),
        migrations.AlterModelOptions(
            name='ecosystem',
            options={'verbose_name': 'Ecosystem', 'verbose_name_plural': 'Ecosystems'},
        ),
        migrations.AlterModelOptions(
            name='ecosystemvariations',
            options={'verbose_name': 'Ecosystem Variation', 'verbose_name_plural': 'Ecosystem Variations'},
        ),
        migrations.AlterModelOptions(
            name='plantae',
            options={'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='taxonomicgroup',
            options={'verbose_name': 'Taxonomic Group', 'verbose_name_plural': 'Taxonomic Groups'},
        ),
    ]
