# Generated by Django 3.2.4 on 2021-06-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimitivaOccupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrimitivaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('primitiva_code', models.CharField(max_length=150)),
                ('identification_photo', models.ImageField(upload_to='staff_media/', verbose_name='photo')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('secondary_last_name', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=150)),
                ('residence_city', models.CharField(max_length=150)),
                ('occupation', models.ManyToManyField(related_name='occupation', through='primitiva_staff.PrimitivaOccupations', to='primitiva_staff.PrimitivaRole', verbose_name='Primitiva Occupation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
