# Generated by Django 3.2.4 on 2021-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primitiva_staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primitivaoccupations',
            options={'verbose_name': 'Primitiva Occupation', 'verbose_name_plural': 'Primitiva Occupations'},
        ),
        migrations.AlterModelOptions(
            name='primitivarole',
            options={'verbose_name': 'Primitiva Role', 'verbose_name_plural': 'Primitiva Roles'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='identification_photo',
            field=models.ImageField(blank=True, upload_to='staff_media/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='primitiva_code',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
