# Generated by Django 3.2.4 on 2021-06-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210611_0445'),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='research_details',
            field=models.ManyToManyField(related_name='research_to_post', to='research.Research', verbose_name='Post Details'),
        ),
    ]
