# Generated by Django 3.2.4 on 2021-06-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatsdetails',
            name='booster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosters', to='research.threatsboosters', verbose_name='Boosters'),
        ),
        migrations.AlterField(
            model_name='threatsdetails',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat', to='research.threats', verbose_name='Threat'),
        ),
    ]
